name: Build Recovery for Samsung GALLLLLALA A10

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Target build'
        required: true
        default: 'recovery_image'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java (if required for the build)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Set up Android SDK (if required)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools-version: 30.0.3

      # Install dependencies if any
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Run makefile to build the specified target
      - name: Build recovery
        run: |
          make clean
          make ${{ github.event.inputs.build_target }}

      # Archive the build output (if needed)
      - name: Upload recovery image
        uses: actions/upload-artifact@v3
        with:
          name: recovery-image
          path: output/recovery.img  # Adjust the path based on where the image is saved
