name: Build Recovery for Samsung Android A10

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Target build type (e.g., recovery_image)'
        required: true
        default: 'recoveryimage'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies if any
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Set up the Android build environment
      - name: Set up Android build environment
        run: |
          source build/envsetup.sh
          lunch omni_a10-eng

      # Run make to build the recovery image
      - name: Build recovery image
        run: |
          make recoveryimage -j$(nproc --all)

      # Archive the build output (if needed)
      - name: Upload recovery image
        uses: actions/upload-artifact@v3
        with:
          name: recovery-image
          path: out/target/product/a10/recovery.img  # Adjust the path based on where the image is saved
