name: Build Recovery 

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Target build type (e.g., recovery_image)'
        required: true
        default: 'recovery_image'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies if any
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Run makefile to build the specified target
      - name: Build recovery
        run: |
          make ${{ github.event.inputs.build_target }}

      # Archive the build output (if needed)
      - name: Upload recovery image
        uses: actions/upload-artifact@v3
        with:
          name: recovery-image
          path: output/recovery.img  # Adjust the path based on where the image is saved
