name: Build and Upload

on:
  workflow_dispatch:
    branches:
      - fox-a10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: fox-a10

      - name: Check for buildenv.sh and execute
        if: ${{ exists('buildenv.sh') }}
        run: |
          chmod +x ./buildenv.sh
          ./buildenv.sh

      - name: Check for build_ofox.sh and execute
        if: ${{ exists('build_ofox.sh') }}
        run: |
          chmod +x ./build_ofox.sh
          ./build_ofox.sh

      - name: Find the created zip file
        run: |
          # Assuming the generated zip is stored in the current directory or subdirectories
          export CREATED_ZIP=$(find . -type f -name "*.zip" | head -n 1)
          echo "CREATED_ZIP=$CREATED_ZIP" >> $GITHUB_ENV

      - name: Upload the zip file to bashupload.com
        run: |
          if [ -z "$CREATED_ZIP" ]; then
            echo "No zip file found to upload."
            exit 1
          fi
          curl bashupload.com -T "$CREATED_ZIP"
